# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SociomileChatSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SociomileChatSDK
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 7.0'
  pod 'NVActivityIndicatorView'

  target 'SociomileChatSDKTests' do
    # Pods for testing

  end

end

target 'SociomileChatSDKApps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SociomileChatSDK
  pod 'SociomileChatSDK', :path => './'

end
