# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sociomile Chat SDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sociomile Chat SDK

  target 'Sociomile Chat SDKTests' do
    # Pods for testing
  end
  
  

end
